### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by phycmcmv** [CITCEuraRFID/KeyDuino#5]
I get this error when compiling an Arduino program that calls this library:

_KeyDuino.cpp:716:77: warning: narrowing conversion of '(((int)len) + 1)' from 'int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]_

Being called from the relay_shield example from that is part Keyduino:
https://github.com/CITCEuraRFID/KeyDuino/tree/master/KeyDuino/examples

Any guidance on how to fix this?

**Comment by RayBor** [comment]
Hi,

This error is very strange. When I compile the code on my PC I don't have any error.
Plus, this seems to indicate a problem on line 716, character 77 of the KeyDuino.cpp file, but there is nothing on this line in the file, and it's part of a function that has nothing to do with the relay_shield example.

Still, it seems to be only a warning and not an error, so that should'nt prevent you from compiling.
Is'nt there anything else on your compile output ?

Ray

**Comment by phycmcmv** [comment]
Thanks Ray - yes, there was this additional error:

...Arduino\libraries\KeyDuino\KeyDuino.cpp:1053:16: error: 'Serial1' was not declared in this scope

```
 _serial = &Serial1;

            ^_
```

**Comment by mrstein** [comment]
Hi, 
Maybe you  didn't select the good board in "tool>board", can you check if you use the correct one (Arduino Leonardo)?

**Comment by phycmcmv** [comment]
Thanks - that solved it.
